### ISSUE TITLE
Singleton Entity Question

### ISSUE THREAD

**Issue by donxu29** [SlashGames/slash-framework#48]
It seems to me that some entities can be singletons so that they are always unique and you don't need an Id to find the component underneath it. Good idea, bad idea? How would I implement it?

**Comment by coeing** [comment]
Hi Don :)

I wouldn't add a generic way for the singleton pattern for entities. It always depends on the specific use case. But in my ears having a component that is only on one entity sounds more like it should be a system instead of an entity. Systems are singletons by default and it may be worth considering.

If you post your specific use case we can discuss it in detail.

**Comment by npruehs** [comment]
I can remember we had some (rare) cases in the past. One of which that comes into my mind is the idea of a "map" entity, which holds information such as the width and height of the map.

In this case, we had a single entity with one or more components holding these properties. The entity was created from a blueprint, so we could load the data from disk.

As soon as the entity was created by some system (e.g. the MapSystem), an event was raised, notifying all other systems of the id of the entity (e.g. MapInitializedEvent, with a single property, Entity = 123).

**Comment by coeing** [comment]
That's true, thanks for the reminder :) In case of the map the thing was that only one map was ever active at the same time, but there were multiple different maps in the game. 

Then it makes sense to handle them as entities, not as a system, and inform the game systems about the creation (and deletion) of a map via events.

**Comment by coeing** [comment]
Closing it as the questions seems to be answered
