### ISSUE TITLE
Question: How is GameEventBehaviour used?

### ISSUE THREAD

**Issue by donxu29** [SlashGames/slash-framework#51]
The class looks interesting, but I'm not sure how it's used in an actual game.

**Comment by npruehs** [comment]
Hey @donxu29, that class is designed as a base class for any Unity code that should rely on game logic events. The basic idea is to allow programmers to create a bridge between the game logic (Slash.ECS) and the Unity client. You can create a class deriving from `GameEventBehaviour`, and implement `RegisterListeners`, calling `RegisterListener` for each event you want to listen to. The `GameEventBehaviour` will take of the rest, e.g. looking up the `GameBehavior` and taking care of registering listeners as soon as an actual `Game` is available, as well as properly removing listeners again in order to avoid subtle bugs memory leaks.

We should think about making that class abstract to communicate that idea by its design.

**Comment by coeing** [comment]
I couldn't have explained it better 👍 Any further questions about the script?

**Comment by coeing** [comment]
Closing it because everything seems to be answered 👍
